version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  public_spree:
  storage:

services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: new_native_password
      command: --default_authentication_plugin=mysql_native_password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: new_native_password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/app
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /app/log
      - /app/tmp
      - vendor_bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - public_spree:/app/public/spree
      - storage:/app/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
